[[redirects]]
  from = "https://komponents-v2.netlify.app"
  to = "https://komponents.ng"
  status = 301
  force = true

[[redirects]]
  from = "https://komponents.com.ng/*"
  to = "https://komponents.ng/:splat"
  status = 301
  force = true

[build]
    command = "npm cache clean --force && npm i --force && npm run build"
    publish = "dist"

[build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "7"